// Code generated by sqlc. DO NOT EDIT.

package db

import (
    "context"
)

type Querier interface {
	CreateBasket(ctx context.Context) (*Basket, *Error)
	GetBasket(ctx context.Context) (*Basket, *Error)
	DeleteBasket(ctx context.Context) *Error
	GetProducts(ctx context.Context) []*Product
	GetProduct(ctx context.Context, id int64) (*Product, *Error)
	AddBasketProduct(ctx context.Context, productID int64) (*Basket, *Error)
	GetBasketProducts(ctx context.Context) ([]*Product, *Error)
}
